package presentacion;

import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import logica.entidades.Palabra;
import logica.util.SimpleList;
import logica.util.Tuple;

/**
 *
 * @author Tyncho
 * @version 1.0
 */
public class DetallePalabra extends javax.swing.JFrame {

    /**
     * Constructor
     *
     * @param palabras
     * @param p
     */
    public DetallePalabra(Palabra p,SimpleList<Tuple> palabras) {
        initComponents();
        this.lblPalabraSeleccionada.setText(p.getDescripcion());
        this.lblAparicionesTotal.setText(String.valueOf(p.getCantidad()));
        mostrarDetalles(palabras);
        
    }

    public void mostrarDetalles(SimpleList<Tuple> frecuenciaXArchivos) {
        if (frecuenciaXArchivos != null) {
            DefaultTableModel dtm = new DefaultTableModel() {

                @Override
                public boolean isCellEditable(int row, int column) {
                    return false; //To change body of generated methods, choose Tools | Templates.
                }

            };
            dtm.setColumnIdentifiers(new String[]{"Archivo", "Frecuencia"});
            Iterator<Tuple> it = frecuenciaXArchivos.iterator();
            Tuple fxa = null;
            while (it.hasNext()) {
                fxa = it.next();
                dtm.addRow(new Object[]{fxa.x, fxa.y});
            }
            tblArchivos.setModel(dtm);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArchivos = new javax.swing.JTable();
        label2 = new java.awt.Label();
        lblPalabraSeleccionada = new javax.swing.JLabel();
        lblAparicionesTotal = new javax.swing.JLabel();

        label1.setText("label1");

        setTitle("Detalle de Palabra");

        tblArchivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Archivo", "Apariciones en Archivo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblArchivos);

        label2.setText("Palabra");

        lblAparicionesTotal.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPalabraSeleccionada)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAparicionesTotal)
                                .addGap(83, 83, 83)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblPalabraSeleccionada)
                            .addGap(20, 20, 20))
                        .addComponent(lblAparicionesTotal, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JLabel lblAparicionesTotal;
    private javax.swing.JLabel lblPalabraSeleccionada;
    private javax.swing.JTable tblArchivos;
    // End of variables declaration//GEN-END:variables
}
